name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          brew update
          brew install llvm clang-format shellcheck shfmt

      - name: Verify tools installation
        run: |
          echo "=== Проверка установленных инструментов ==="
          clang --version
          /opt/homebrew/opt/llvm/bin/clang-tidy --version
          clang-format --version

      - name: Check shell
        run: make shell-check

      - name: Check clang-format
        run: make format

      - name: clang-tidy
        run: make clang-tidy

      - name: Build all
        run: make build

      - name: Test all (sanitizers)
        run: make test
